# Generated by Django 6.0.1 on 2026-02-02 18:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='free_days_count',
            field=models.IntegerField(default=0, verbose_name='Dias de Estagiário Usados'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
